spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/auto/auto.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
